### PR TITLE
remote: fix connhelpers with custom dialer

### LINKED ISSUE #2324: [0.13] remote driver with kube-pod URL is stuck at inactive
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

docker-buildx 0.13.0 could not detect the buildkit 0.13.0 instance on kubernetes via `kube-pod://` URL. It works well if I kubectl port-forward the service into local and use `tcp://127.0.0.1:1234`.

### Expected behaviour

docker buildx 0.13.0 supports remote driver with kube-pod as in 0.12.1

### Actual behaviour

Remote builder is stuck at inactive when using kube-pod:// URL

### Buildx version

github.com/docker/buildx v0.13.0 Homebrew

### Docker info

```text
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    colima
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.0
    Path:     /.../.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.24.7
    Path:     /.../.docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 4
  Paused: 0
  Stopped: 5
 Images: 64
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-17-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 7.736GiB
 Name: colima
 ID: 0296b23e-9bd3-4597-918d-0c64e567f14e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
NAME/NODE          DRIVER/ENDPOINT                                                                                            STATUS     BUILDKIT               PLATFORMS
kube-chulki        kubernetes
 \_ kube-chulki0    \_ kubernetes:///kube-chulki?deployment=buildkit-4217ad63-0d28-4fdd-8dcf-9bf48ea1bf71-chtgj&kubeconfig=   running    v0.12.5                linux/arm64, linux/arm/v7, linux/arm/v6
 \_ kube-chulki0    \_ kubernetes:///kube-chulki?deployment=buildkit-4217ad63-0d28-4fdd-8dcf-9bf48ea1bf71-chtgj&kubeconfig=   running    v0.12.5                linux/arm64, linux/arm/v7, linux/arm/v6
 \_ kube-chulki0    \_ kubernetes:///kube-chulki?deployment=buildkit-4217ad63-0d28-4fdd-8dcf-9bf48ea1bf71-chtgj&kubeconfig=   running    v0.12.5                linux/arm64, linux/arm/v7, linux/arm/v6
 \_ kube-chulki0    \_ kubernetes:///kube-chulki?deployment=buildkit-4217ad63-0d28-4fdd-8dcf-9bf48ea1bf71-chtgj&kubeconfig=   running    v0.12.5                linux/arm64, linux/arm/v7, linux/arm/v6
remote*            remote
 \_ remote0         \_ kube-pod://buildkitd-amd64-0?namespace=buildkit&context=............                                   inactive
remote-tcp         remote
 \_ remote-tcp0     \_ tcp://127.0.0.1:1234                                                                                   running    v0.13.0                linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/386
colima             docker
 \_ colima          \_ colima                                                                                                 running    v0.11.7+d3e6c1360f6e   linux/arm64, linux/amd64, linux/amd64/v2
default                                                                                                                       error

Cannot load builder default: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Configuration

N/A

### Build logs

_No response_

### Additional info

- I deployed builkit using https://github.com/moby/buildkit/blob/v0.13.0/examples/kubernetes/statefulset.privileged.yaml
- docker-buildx 0.12.1 + buildkit 0.13.0 worked.
- docker-buildx 0.13.0 + buildkit 0.12.5 didn't work
  - kubernetes driver bootstrap a builder using `moby/buildkit:buildx-1-stabe` which is 0.12.5.. so I thought it could be compatible issue but it's actually not

Found different behavior with dial-stdio which is apparently used to connect to builder

```console
$ docker-buildx dial-stdio --builder remote-tcp --progress plain
#0 builder: remote-tcp

#1 Proxying to builder
#1 Dialing builder
#1 Dialing builder 1.8s done

$ docker-buildx dial-stdio --builder remote --progress plain
#0 builder: remote

#1 Proxying to builder
#1 Dialing builder
#1 ...

#2 [internal] waiting for connection
#2 ERROR: context deadline exceeded

#1 Proxying to builder
#1 Dialing builder 20.0s done
#1 ERROR: context deadline exceeded
------
 > Proxying to builder:
------
------
 > [internal] waiting for connection:
------
ERROR: context deadline exceeded
```

I'm not sure it's a buildkit issue or docker-buildx issue though.

### PR DESCRIPTION
**Pull request by tonistiigi**
fix #2324
closes #2329

With the new dial-stdio command the dialer is split from `Client` function in order to access it directly.

This breaks the custom connhelpers functionality
as support for connhelpers is a feature of the default dialer. If client defines a custom dialer then only it is used without extra modifications. This means that remote driver dialer needs to detect the
connhelpers on its own.

The relevant default dialer addition is in https://github.com/moby/buildkit/blob/a38011b9f57db4b805e6bb0322d7d923b341bc6e/client/client.go#L109-L115 .

@cpuguy83 @jsternberg 

@crazy-max For test, should we have one custom test just for connhelpers or maybe just add extra config in the matrix that runs remote driver with a `docker-container://` endpoint address?

### CODE REVIEW

**Comment by crazy-max** [comment]
> For test, should we have one custom test just for connhelpers or maybe just add extra config in the matrix that runs remote driver with a `docker-container://` endpoint address?

I think a custom test is fine, I will open a PR with this test to make it fail.

File: tests/create.go [hunk 1]
```diff
@@ -57,3 +60,28 @@ func testCreateRestartAlways(t *testing.T, sb integration.Sandbox) {
...
+	if sb.Name() != "docker" {
+		t.Skip("skipping test for non-docker workers")
+	}
+
+	var builderName string
+	t.Cleanup(func() {
+		if builderName == "" {
+			return
+		}
+		out, err := rmCmd(sb, withArgs(builderName))
```
Comment (tonistiigi) [inline tests/create.go:74]: This should clean up both builders?

File: tests/create.go [hunk 2]
```diff
@@ -57,3 +60,28 @@ func testCreateRestartAlways(t *testing.T, sb integration.Sandbox) {
...
+
+	out, err := createCmd(sb, withArgs("--driver", "docker-container"))
+	require.NoError(t, err, out)
+	builderName = strings.TrimSpace(out)
+
+	out, err = inspectCmd(sb, withArgs("--bootstrap", builderName))
+	require.NoError(t, err, out)
+
+	out, err = createCmd(sb, withArgs("--driver", "remote", fmt.Sprintf("docker-container://%s_%s0", driver.BuilderNamePrefix, builderName), "--bootstrap"))
+	require.NoError(t, err, out)
```
Comment (tonistiigi) [inline tests/create.go:86]: For a good measure I think better to do `--name <randomname>` and then extra check with  `inspect <randomname>`. Maybe also check that the remote builder is in the running state.

Comment (crazy-max) [reply tests/create.go:98]: Updated to return builder name from output and inspect after.

**Comment by crazy-max** [comment]
#2329 fails as expected: https://github.com/docker/buildx/actions/runs/8215998277/job/22470095437?pr=2329#step:7:163

**Review by crazy-max — APPROVED** [review]

File: tests/create.go [hunk 3]
```diff
@@ -57,3 +61,39 @@ func testCreateRestartAlways(t *testing.T, sb integration.Sandbox) {
...
+
+	cmd := dockerCmd(sb, withArgs("container", "inspect", fmt.Sprintf("%s%s0", driver.BuilderNamePrefix, ctnBuilderName)))
+	cmd.Stderr = os.Stderr
+	require.NoError(t, cmd.Run())
+
+	out, err = createCmd(sb, withArgs("--driver", "remote", fmt.Sprintf("docker-container://%s%s0", driver.BuilderNamePrefix, ctnBuilderName), "--bootstrap"))
+	require.NoError(t, err, out)
+	remoteBuilderName = strings.TrimSpace(out)
+
+	out, err = inspectCmd(sb, withArgs("--bootstrap", remoteBuilderName))
```
Comment (tonistiigi) [inline tests/create.go:97]: This does not need bootstrap (actually the `create` in line 93 doesn't as well).

If we use a generated name for both builders then for extra safety check that the names are not the same and this line isn't just checking the first builder again.

Comment (crazy-max) [reply tests/create.go:97]: > then for extra safety check that the names are not the same

Don't think they can be the same, we have a check in store logic for this when generating name: https://github.com/docker/buildx/blob/4327ee73b18949e47eb1c865daa262af095cf974/store/util.go#L40-L54

Comment (crazy-max) [reply tests/create.go:97]: > This does not need bootstrap (actually the `create` in line 93 doesn't as well).

My bad forgot to remove this arg

Comment (tonistiigi) [reply tests/create.go:97]: Yes, but the reason for the check is to detect the case if this code breaks.

**Review by cpuguy83 — APPROVED** [review]

File: tests/create.go (hunk 2 above)
Comment (tonistiigi) [reply tests/create.go:101]: Check that the second builder is in running state as well.

**Review by tonistiigi — COMMENTED** [review]
Test LGTM

File: builder/node.go [hunk 4]
```diff
@@ -142,7 +142,7 @@ func (b *Builder) LoadNodes(ctx context.Context, opts ...LoadNodesOption) (_ []N
 					}
 				}
 
-				d, err := driver.GetDriver(ctx, "buildx_buildkit_"+n.Name, factory, n.Endpoint, dockerapi, imageopt.Auth, kcc, n.BuildkitdFlags, n.Files, n.DriverOpts, n.Platforms, b.opts.contextPathHash, lno.dialMeta)
+				d, err := driver.GetDriver(ctx, driver.BuilderNamePrefix+n.Name, factory, n.Endpoint, dockerapi, imageopt.Auth, kcc, n.BuildkitdFlags, n.Files, n.DriverOpts, n.Platforms, b.opts.contextPathHash, lno.dialMeta)
```
Comment (jsternberg) [inline builder/node.go:145]: Instead of using a constant and doing `driver.BuilderNamePrefix+n.Name`, maybe we should have:

```
func BuilderName(name string) string {
}
```

Functionally it would do the same thing, but it would avoid leaking that these are a simple concatenation and make the library a bit easier to use correctly.

**Review by jsternberg — APPROVED** [review]
LGTM. A few comments on some refactoring ideas that I think would be minor and good to implement, but nothing blocking.

**Review by jsternberg — APPROVED** [review]
