### PR TITLE
driver(docker-container): fix incorrect path when writing certs

### LINKED ISSUE #1827: docker buildx build error "The directory name is invalid."
### Discussed in https://github.com/docker/buildx/discussions/1808

<div type='discussions-op-text'>

<sup>Originally posted by **mkim0203** May 17, 2023</sup>
1. create 
   docker buildx create --use --driver=docker-container --name=hc-bulid --config /https/buildkit-hc-build.toml
2. build
   docker buildx build -t test.com:30008/temp/backendapi:0.0.1 -f C:\src\Dockerfile.gen --cache-to type=local,dest=/data/docker-cache --cache-from type=local,src=/data/docker-cache C:\src --push --provenance=false

[+] Building 2.2s (1/1) FINISHED
 **=> ERROR [internal] booting buildkit**                                                                                                                                                       
 => => pulling image moby/buildkit:buildx-stable-1
 => => creating container buildx_buildkit_hc-bulid0
ERROR: mkdir C:\Users\mhkim\AppData\Local\Temp\buildkitd-config1566081107\etc\buildkit\certs\test.com:30008: The directory name is invalid.

* buildx version : github.com/docker/buildx v0.10.4 c513d34049e499c53468deac6c4267ee72948f02
* os : windows 11
* config file 
## buildkit-hc-build.toml
[registry."test.com:30008"]
  ca=["/https/host-ssl.crt"]

이것은 버그 인가요? 윈도우 환경에서 디렉토리 이름에 ":"가 들어갈수 없어서 발생되는 현상으로 보입니다. ubuntu 에서 같은 방법으로 진행시 에러가 발생하지 않습니다.
========
is this a bug? It seems to be a phenomenon that ":" cannot be entered in the directory name in the Windows environment. When proceeding in the same way in ubuntu, no error occurs.

</div>

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #1827 

Replace invalid characters in the name of the base directory of certificates using the name of the registry which can contain for example a colon when the port is specified.

### CODE REVIEW

File: util/confutil/container.go [hunk 1]
```diff
@@ -60,7 +63,7 @@ func LoadConfigFiles(bkconfig string) (map[string][]byte, error) {
 			if regConf == nil {
 				continue
 			}
-			pfx := path.Join("certs", regName)
+			pfx := path.Join("certs", reInvalidCertsDir.ReplaceAllString(regName, "_"))
```
Comment (thaJeztah) [inline util/confutil/container.go:66]: IIRC, the engine uses the (awkward) `:` as-is for Linux, but on Windows it strips it; https://github.com/moby/moby/blob/6e98a7f2c9184d4e91df8abf06e2245a0cd77c58/registry/config_windows.go#L12-L20

**Review by jedevc — APPROVED** [review]
