### PR TITLE
ls: fix duplicated builders for json format

### LINKED ISSUE #2969: "docker buildx ls --format json" generates invalid JSON and lists each entry twice
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

- The output of `docker buildx ls --format json` should be an array, but it's a concatenation of separate JSON objects, one per builder instance
- `docker buildx ls --format json` lists each entry twice whereas `docker buildx ls` works properly

I am on MacOS-13.7.3 and the `buildx` version is: `github.com/docker/buildx v0.19.2-desktop.1 412cbb151f1be3f8a94dc4eb03cd1b67f261dec5`

### Expected behaviour

When I ran `docker buildx ls --format json`, I should see two entries in a JSON array (each entry truncated with ellipsis for brevity):
```json
[
{"Name":"default","Driver":"docker", ...},
{"Name":"desktop-linux","Driver":"docker", ...}
]
```
This expected output should match `docker buildx ls` (table format) , i.e. two entries, not four.
```console
$ docker buildx ls
NAME/NODE           DRIVER/ENDPOINT     STATUS    BUILDKIT   PLATFORMS
default             docker
 \_ default          \_ default         running   v0.17.3    linux/amd64 (+3), linux/arm64, linux/arm (+2), linux/ppc64le, (2 more)
desktop-linux*      docker
 \_ desktop-linux    \_ desktop-linux   running   v0.17.3    linux/amd64 (+3), linux/arm64, linux/arm (+2), linux/ppc64le, (2 more)
```

### Actual behaviour

...instead, I see :
```json
{"Name":"default","Driver":"docker", ...}
{"Name":"default","Driver":"docker", ...}
{"Name":"desktop-linux","Driver":"docker", ...}
{"Name":"desktop-linux","Driver":"docker", ...}
```
- entries are separate standalone JSON objects, but should be members of an array
- entries are listed twice
This results is JSON validation failure:
```console
Error: Parse error on line 1:
...er":"overlayfs"}}]}{"Name":"default","D
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```
Or checking with `json.tool`:
```console
$ docker buildx ls --format json | python -m json.tool
Extra data: line 2 column 1 (char 1417)
```
The full output result of `docker buildx ls --format json` is attached:
[buildx_ls_out.json](https://github.com/user-attachments/files/18691003/buildx_ls_out.json)

### Buildx version

github.com/docker/buildx v0.19.2-desktop.1 412cbb151f1be3f8a94dc4eb03cd1b67f261dec5

### Docker info

```text
Client:
 Version:    27.4.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Ask Gordon - Docker Agent (Docker Inc.)
    Version:  v0.5.1
    Path:     /Users/wolf2/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.2-desktop.1
    Path:     /Users/wolf2/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0-desktop.2
    Path:     /Users/wolf2/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     /Users/wolf2/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Beta) (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/wolf2/.docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/wolf2/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     /Users/wolf2/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /Users/wolf2/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     /Users/wolf2/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/wolf2/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.15.1
    Path:     /Users/wolf2/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 27.4.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.655GiB
 Name: docker-desktop
 ID: a9d33cb0-17b0-4031-9f64-34b0bd1774f3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/wolf2/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Builders list

```text
NAME/NODE           DRIVER/ENDPOINT     STATUS    BUILDKIT   PLATFORMS
default             docker
 \_ default          \_ default         running   v0.17.3    linux/amd64 (+3), linux/arm64, linux/arm (+2), linux/ppc64le, (2 more)
desktop-linux*      docker
 \_ desktop-linux    \_ desktop-linux   running   v0.17.3    linux/amd64 (+3), linux/arm64, linux/arm (+2), linux/ppc64le, (2 more)
```

### Configuration

`mininal_dockerfile.txt`:
```dockerfile
FROM scratch
```
```console
$ docker buildx build --progress plain -f mininal_dockerfile.txt .
#0 building with "desktop-linux" instance using docker driver

#1 [internal] load build definition from mininal_dockerfile.txt
#1 transferring dockerfile: 62B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 98B done
#2 DONE 0.0s

#3 exporting to image
#3 exporting layers done
#3 exporting manifest sha256:3a58ad119f0dae830e39299dd9d94100e3a764665fba8810f9a873d3ac716aec done
#3 exporting config sha256:471a1b8817eefb6569017c1a76f288e0d4e5c8476eb199485c469d0b033168bf done
#3 naming to moby-dangling@sha256:3a58ad119f0dae830e39299dd9d94100e3a764665fba8810f9a873d3ac716aec done
#3 DONE 0.0s

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/b814b21gpa45p9hto49guhayn
```

### Build logs

```text
N/A - not a build issue
```

### Additional info

I searched is this was already reported, but didn't find anything, or I didn't search properly.

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #2969 

JSON format for `ls` command without Go template (`--format json`) should not set nodes in formatter context.

### CODE REVIEW

File: commands/ls.go [hunk 1]
```diff
@@ -159,6 +159,9 @@ func lsPrint(dockerCli command.Cli, current *store.NodeGroup, builders []*builde
 				}
 				continue
 			}
+			if ctx.Format.IsJSON() {
```
Comment (tonistiigi) [inline commands/ls.go:162]: So JSON output does not allow seeing multi-node builders and their properties/endpoints?

Comment (crazy-max) [reply commands/ls.go:162]: `json` format marshals the builder with list of nodes: https://github.com/docker/buildx/blob/0a4eb7ec762ba329d48025f497a1539b25f47617/commands/ls.go#L211-L213

```
{
   "Name":"builder",
   "Driver":"docker-container",
   "LastActivity":"2025-02-06T15:15:12Z",
   "Dynamic":false,
   "Nodes":[
      {
         "Name":"builder0",
         "Endpoint":"unix:///var/run/docker.sock",
         "Flags":[
            "--debug",
            "--allow-insecure-entitlement",
            "security.insecure",
            "--allow-insecure-entitlement",
            "network.host"
         ],
         "DriverOpts":{
            "env.BUILDKIT_STEP_LOG_MAX_SIZE":"10485760",
            "env.BUILDKIT_STEP_LOG_MAX_SPEED":"10485760",
            "env.JAEGER_TRACE":"localhost:6831",
            "image":"moby/buildkit:master"
         },
         "Status":"running",
         "Version":"4b36562",
         "IDs":[
            "v6u0iluh9v6ixuqwvybs60qzj"
         ],
         "Platforms":[
            "linux/amd64",
            "linux/amd64/v2",
            "linux/amd64/v3",
            "linux/arm64",
            "linux/riscv64",
            "linux/ppc64le",
            "linux/s390x",
            "linux/386",
            "linux/arm/v7",
            "linux/arm/v6"
         ],
         "GCPolicy":[
            {
               "all":false,
               "filter":[
                  "type==source.local,type==exec.cachemount,type==source.git.checkout"
               ],
               "keepDuration":172800000000000,
               "reservedSpace":0,
               "maxUsedSpace":512000000,
               "minFreeSpace":0
            },
            {
               "all":false,
               "filter":null,
               "keepDuration":5184000000000000,
               "reservedSpace":10000000000,
               "maxUsedSpace":100000000000,
               "minFreeSpace":202000000000
            },
            {
               "all":false,
               "filter":null,
               "keepDuration":0,
               "reservedSpace":10000000000,
               "maxUsedSpace":100000000000,
               "minFreeSpace":202000000000
            },
            {
               "all":true,
               "filter":null,
               "keepDuration":0,
               "reservedSpace":10000000000,
               "maxUsedSpace":100000000000,
               "minFreeSpace":202000000000
            }
         ],
         "Labels":{
            "org.mobyproject.buildkit.worker.executor":"oci",
            "org.mobyproject.buildkit.worker.hostname":"e885c15d9fbc",
            "org.mobyproject.buildkit.worker.network":"host",
            "org.mobyproject.buildkit.worker.oci.process-mode":"sandbox",
            "org.mobyproject.buildkit.worker.selinux.enabled":"false",
            "org.mobyproject.buildkit.worker.snapshotter":"overlayfs"
         }
      }
   ]
}
```

While table and go template output has an entry for each builder and node. This is similar to what `docker service ps` does: https://docs.docker.com/reference/cli/docker/service/ps/#examples.
