### PR TITLE
Fix --pull and --no-cache behavior

### LINKED ISSUE #265: [v0.4.0] build fail with --pull arg
Hi,

with the last version (v0.4.0) there is a problem with the build command when I use it whith --pull arg, I guess that there is command parsing problem:

```shell
docker buildx build   --target dev   --tag my_tag --pull --load .
invalid argument "--load" for "--pull" flag: strconv.ParseBool: parsing "--load": invalid syntax
```

If I had ```true``` just after ```--pull``` arg it works:

```shell
docker buildx build   --target dev   --tag my_tag --pull true --load .
```

### PR DESCRIPTION
**Pull request by tiborvass**
Fixes --pull and --no-cache without argument

Signed-off-by: Tibor Vass <tibor@docker.com>

Fixes #265

### CODE REVIEW

File: commands/build.go [hunk 1]
```diff
@@ -305,9 +333,9 @@ func buildCmd(dockerCli command.Cli, rootOpts *rootOptions) *cobra.Command {
 }
 
 func commonBuildFlags(options *commonOptions, flags *pflag.FlagSet) {
-	flags.Var(flagutil.Tristate(options.noCache), "no-cache", "Do not use cache when building the image")
+	options.noCache = flags.Bool("no-cache", false, "Do not use cache when building the image")
 	flags.StringVar(&options.progress, "progress", "auto", "Set type of progress output (auto, plain, tty). Use plain to show container output")
-	flags.Var(flagutil.Tristate(options.pull), "pull", "Always attempt to pull a newer version of the image")
+	options.pull = flags.Bool("pull", false, "Always attempt to pull a newer version of the image")
```
Comment (thaJeztah) [inline commands/build.go:338]: Curious; wouldn't something like this work?

```go
flags.StringVar(&options.pull, "pull", nil, "Always attempt to pull a newer version of the image")
```

(use `nil` as default)?

Comment (tiborvass) [reply commands/build.go:338]: You'd have to do an strconv.ParseBool which flags.Bool does for us.

File: bake/bake.go [hunk 2]
```diff
@@ -348,8 +348,8 @@ type Target struct {
 	SSH        []string          `json:"ssh,omitempty" hcl:"ssh,optional"`
 	Platforms  []string          `json:"platforms,omitempty" hcl:"platforms,optional"`
 	Outputs    []string          `json:"output,omitempty" hcl:"output,optional"`
-	Pull       bool              `json:"pull,omitempty": hcl:"pull,optional"`
```
Comment (tiborvass) [inline bake/bake.go:351]: @thaJeztah check out this stupidity!!!! 😠
