### PR TITLE
driver/kubernetes: Add retry logic for transient TLS connection errors

### LINKED ISSUE #2668: buildx kubernetes driver sometimes returns `ERROR: error dialing backend: remote error: tls: internal error`
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

On EKS 1.29 specifically using ARM64 nodes, it seems that there exists a race condition somewhere where the node CSR is not signed yet but the node is reported as ready in the cluster. 
The issue goes away after a number of seconds once the CSR is approved and issued.
However, during that time all calls to the pods situated on the node return the above mentioned error. 
Buildx kubernetes driver specifically returns this:
```
ERROR: error dialing backend: remote error: tls: internal error
ERROR: context deadline exceeded

NAME/NODE                             DRIVER/ENDPOINT                                                                                                               STATUS    BUILDKIT   PLATFORMS
buildx-php-release-8.2-2b0efca        kubernetes                                                                                                                                         
 \_ buildx-php-release-8.2-2b0efca0    \_ kubernetes:///buildx-php-release-8.2-2b0efca?deployment=buildkit-8e44b51e-ee72-4a03-873b-8fa232cf24d9-33fdb&kubeconfig=   running   v0.15.2    linux/amd64*
 \_ buildx-php-release-8.2-2b0efca1    \_ kubernetes:///buildx-php-release-8.2-2b0efca?deployment=buildkit-b4c6a857-d35e-4171-b4d3-0e38e1749975-05a58&kubeconfig=   error                linux/arm64*
Failed to get status for buildx-php-release-8.2-2b0efca (buildx-php-release-8.2-2b0efca1): listing workers: failed to list workers: DeadlineExceeded: context deadline exceeded
default*                              docker                                                                                                                                             
 \_ default                            \_ default                                                                                                                   running   v0.15.2    linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```
I was browsing the buildx source code and found the call to list the workers: https://github.com/docker/buildx/blob/master/vendor/github.com/moby/buildkit/client/workers.go#L31 
But it's not clear what the retry logic is here. It seems to me when we get the above tls internal error, the code just dies and buildx quits.
Is it possible to handle this specific error somehow? It's transient, and should succeed if buildx does some kind of exponential backoff.

buildx is started as follows:
```
docker buildx create --bootstrap --name=buildx-${DOCKERFILE_DIR_SANITIZED}-${VERSION} --driver=kubernetes --platform=linux/amd64 \
         --buildkitd-flags '--debug --trace' \
         --driver-opt='"annotations=karpenter.sh/do-not-disrupt=true,karpenter.sh/do-not-evict=true","image=162166941288.dkr.ecr.us-east-1.amazonaws.com/moby/buildkit:v0.15.2","timeout=[60](https://github.com/activated-insights/docker-base/actions/runs/10648269050/job/29517154748#step:6:60)0s","requests.memory=28Gi","nodeselector=runners=dedicated,kubernetes.io/arch=amd64","tolerations=key=runners,value=dedicated"'
  sleep 10
  docker buildx ls
  docker buildx create --append --bootstrap --name=buildx-${DOCKERFILE_DIR_SANITIZED}-${VERSION} --driver=kubernetes --platform=linux/arm64 \
         --buildkitd-flags '--debug --trace' \
         --driver-opt='"annotations=karpenter.sh/do-not-disrupt=true,karpenter.sh/do-not-evict=true","image=1[62](https://github.com/activated-insights/docker-base/actions/runs/10648269050/job/29517154748#step:6:62)166941288.dkr.ecr.us-east-1.amazonaws.com/moby/buildkit:v0.15.2","timeout=600s","requests.memory=28Gi","nodeselector=runners=dedicated,kubernetes.io/arch=arm[64](https://github.com/activated-insights/docker-base/actions/runs/10648269050/job/29517154748#step:6:64)","tolerations=key=runners,value=dedicated;key=arch,value=arm64"'
  sleep 10
  docker buildx ls
```
buildx and docker versions:
buildkit remote agent to be booted on the nodes: `moby/buildkit:v0.15.2`
docker version: `docker/library/docker:27.2-dind` with its built-in buildkit, no modifications.
The whole setup runs on self-hosted github-actions runners using `0.9.3` version of oci://ghcr.io/actions/actions-runner-controller-charts

It seems to only happen under heavy load on the cluster. We have a repo where we build about 20-30 docker images in parallel (its our base images repo). Each docker image requests 2 buildx kubernetes workers, one for amd64 and one for arm64. So a lot of nodes get spun up at the same time. 

### Expected behaviour

buildx to not die when it encounters a transient error.

### Actual behaviour

Failure log follows:
```
#1 [internal] booting buildkit
W0831 21:09:50.507151     230 warnings.go:70] metadata.name: this is used in Pod names and hostnames, which can result in surprising behavior; a DNS label is recommended: [must not contain dots]
#1 waiting for 1 pods to be ready, timeout: 10 minutes
#1 waiting for 1 pods to be ready, timeout: 10 minutes 66.8s done
#1 DONE 66.8s
buildx-php-release-8.2-2b0efca
NAME/NODE                             DRIVER/ENDPOINT                                                                                                               STATUS    BUILDKIT   PLATFORMS
buildx-php-release-8.2-2b0efca        kubernetes                                                                                                                                         
 \_ buildx-php-release-8.2-2b0efca0    \_ kubernetes:///buildx-php-release-8.2-2b0efca?deployment=buildkit-8e44b51e-ee72-4a03-873b-8fa232cf24d9-33fdb&kubeconfig=   running   v0.15.2    linux/amd64*
default*                              docker                                                                                                                                             
 \_ default                            \_ default                                                                                                                   running   v0.15.2    linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
#1 [internal] booting buildkit
W0831 21:11:07.543695     328 warnings.go:70] metadata.name: this is used in Pod names and hostnames, which can result in surprising behavior; a DNS label is recommended: [must not contain dots]
#1 waiting for 1 pods to be ready, timeout: 10 minutes
#1 waiting for 1 pods to be ready, timeout: 10 minutes 71.9s done
#1 DONE 71.9s
buildx-php-release-8.2-2b0efca
ERROR: error dialing backend: remote error: tls: internal error
ERROR: context deadline exceeded
```
Sometimes it is able to proceed past this error (i'm guessing due to the sleep 10 statement), but not always.

### Buildx version

github.com/dockerbuildx v0.16.2 99dea6dacacc3d604788953088560b9880550570

### Docker info

```text
/ # docker info
Client:
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/local/libexec/docker/cli-plugins/docker-compose
```

### Builders list

```text
NAME/NODE                             DRIVER/ENDPOINT                                                                                                               STATUS    BUILDKIT   PLATFORMS
buildx-php-release-8.2-2b0efca        kubernetes                                                                                                                                         
 \_ buildx-php-release-8.2-2b0efca0    \_ kubernetes:///buildx-php-release-8.2-2b0efca?deployment=buildkit-8e44b51e-ee72-4a03-873b-8fa232cf24d9-33fdb&kubeconfig=   running   v0.15.2    linux/amd64*
 \_ buildx-php-release-8.2-2b0efca1    \_ kubernetes:///buildx-php-release-8.2-2b0efca?deployment=buildkit-b4c6a857-d35e-4171-b4d3-0e38e1749975-05a58&kubeconfig=   error                linux/arm64*
Failed to get status for buildx-php-release-8.2-2b0efca (buildx-php-release-8.2-2b0efca1): listing workers: failed to list workers: DeadlineExceeded: context deadline exceeded
default*                              docker                                                                                                                                             
 \_ default                            \_ default                                                                                                                   running   v0.15.2    linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

### Configuration

```
FROM public.ecr.aws/docker/library/php:8.2-apache

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update &&\
    apt-get -y install gnupg git unzip


### Build logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Guimove**
Fixes #2668

When Kubernetes marks nodes as "Ready" before their Certificate Signing Requests (CSRs) are approved, the buildx kubernetes driver can fail to connect to builder pods with transient TLS errors like:
  - "tls: internal error"
  - "context deadline exceeded"
  - "use of closed network connection"
  - "i/o timeout"

This is particularly problematic on EKS clusters with ARM64 nodes under heavy load, where multiple builders are being spawned simultaneously.

This commit adds retry logic with exponential backoff to the Dial() function in the kubernetes driver. The implementation:
  - Attempts up to 5 connection retries
  - Uses exponential backoff starting at 500ms, capped at 10s
  - Only retries on known transient connection errors
  - Logs retry attempts to stderr for visibility
  - Respects context cancellation

This allows buildx to gracefully handle the race condition where pods are marked as Running before their TLS certificates are fully ready.

### CODE REVIEW

File: driver/kubernetes/driver.go [hunk 1]
```diff
@@ -212,11 +213,59 @@ func (d *Driver) Dial(ctx context.Context) (net.Conn, error) {
...
+		}
+
+		// Calculate delay with exponential backoff
+		delay := time.Duration(1<<uint(attempt)) * baseDelay
+		if delay > maxDelay {
+			delay = maxDelay
+		}
+
+		// Log the retry
+		fmt.Fprintf(os.Stderr, "Transient connection error to pod %s (attempt %d/%d): %v. Retrying in %v...\n",
```
Comment (tonistiigi) [inline driver/kubernetes/driver.go]: Any logs need to go through logrus

File: driver/kubernetes/driver.go [hunk 2]
```diff
@@ -212,11 +213,59 @@ func (d *Driver) Dial(ctx context.Context) (net.Conn, error) {
 	}
 	containerName := pod.Spec.Containers[0].Name
 	cmd := []string{"buildctl", "dial-stdio"}
-	conn, err := execconn.ExecConn(ctx, restClient, restClientConfig, pod.Namespace, pod.Name, containerName, cmd)
-	if err != nil {
-		return nil, err
+
+	// Retry logic for transient TLS errors
```
Comment (tonistiigi) [inline driver/kubernetes/driver.go]: it would be better refactor this to helper like

```
err := tryWithBackoff(func() {
  ExecConn()
})
```

File: driver/kubernetes/driver.go [hunk 3]
```diff
@@ -212,11 +214,81 @@ func (d *Driver) Dial(ctx context.Context) (net.Conn, error) {
...
+
+		lastErr = err
+
+		if !isTransientConnectionError(err) {
+			return nil, err
+		}
+
+		if attempt < maxRetries-1 {
+			delay := calculateBackoff(attempt, baseDelay, maxDelay)
+			fmt.Fprintf(os.Stderr, "Transient connection error to pod %s (attempt %d/%d): %v. Retrying in %v...\n",
```
Comment (tonistiigi) [inline driver/kubernetes/driver.go]: Any logs need to go through logrus

File: driver/kubernetes/driver.go [hunk 4]
```diff
@@ -212,11 +214,81 @@ func (d *Driver) Dial(ctx context.Context) (net.Conn, error) {
...
+func calculateBackoff(attempt int, baseDelay, maxDelay time.Duration) time.Duration {
+	delay := time.Duration(1<<uint(attempt)) * baseDelay
+	if delay > maxDelay {
+		delay = maxDelay
+	}
+	return delay
+}
+
+// waitWithContext waits for the specified duration or until context is cancelled.
+func waitWithContext(ctx context.Context, delay time.Duration) error {
```
Comment (tonistiigi) [inline driver/kubernetes/driver.go]: Extra function for this snippet doesn't seem to add much.

File: driver/kubernetes/driver.go [hunk 5]
```diff
@@ -212,11 +214,81 @@ func (d *Driver) Dial(ctx context.Context) (net.Conn, error) {
 	}
 	containerName := pod.Spec.Containers[0].Name
 	cmd := []string{"buildctl", "dial-stdio"}
-	conn, err := execconn.ExecConn(ctx, restClient, restClientConfig, pod.Namespace, pod.Name, containerName, cmd)
-	if err != nil {
-		return nil, err
+
+	// Retry connection with exponential backoff for transient errors
+	// See https://github.com/docker/buildx/issues/2668
+	return d.dialWithRetry(ctx, restClient, restClientConfig, pod.Namespace, pod.Name, containerName, cmd)
```
Comment (tonistiigi) [inline driver/kubernetes/driver.go]: You can consider pattern like:

```
err := tryWithBackoff(func() {
  ExecConn()
})
```

to avoid method with lots of parameters.

Comment (Guimove) [reply driver/kubernetes/driver.go]: Thanks you @tonistiigi

File: driver/kubernetes/driver.go [hunk 6]
```diff
@@ -212,11 +213,74 @@ func (d *Driver) Dial(ctx context.Context) (net.Conn, error) {
...
+	if err == nil {
+		return false
+	}
+	errStr := err.Error()
+	return strings.Contains(errStr, "tls: internal error") ||
+		strings.Contains(errStr, "context deadline exceeded") ||
+		strings.Contains(errStr, "use of closed network connection") ||
+		strings.Contains(errStr, "i/o timeout") ||
+		strings.Contains(errStr, "connection refused") ||
+		strings.Contains(errStr, "connection reset")
```
Comment (AkihiroSuda) [inline driver/kubernetes/driver.go]: Ideally we should use `errors.Is` (or `errors.As`)

**Comment by AkihiroSuda** [comment]
Please squash the commits

**Comment by Oliniusz** [comment]
@Guimove - would you be able to continue with merging the PR in the close future, please?

**Comment by Guimove** [comment]
> @Guimove - would you be able to continue with merging the PR in the close future, please?

Will resolve the comments from @AkihiroSuda today so as soon it's validated it could be merged.

**Comment by AkihiroSuda** [comment]
DCO check seems failing

**Comment by Guimove** [comment]
@AkihiroSuda it's fixed

**Comment by Guimove** [comment]
@AkihiroSuda Thanks for the validation, who can merge now ? (seems not me)

**Comment by Oliniusz** [comment]
I'd like to confirm it's been working well now! Thank you.

```
[trends-qa-test-11-cpu-amd64 internal] booting buildkit
waiting for 1 pods to be ready, timeout: 2 minutes 39.6s done
DONE 39.6s
ERROR: error dialing backend: remote error: tls: internal error
ERROR: error dialing backend: remote error: tls: internal error
trends-qa-test-11
```
