### PR TITLE
bake: local dockerfile support for remote definition

### LINKED ISSUE #1627: [BUG] Bake build fails when using BAKE_CMD_CONTEXT locally
I noticed that when I use the `BAKE_CMD_CONTEXT` built-in variable in a local HCL bake file, the build fails.

**Steps to reproduce:**
1. Create a Dockerfile (named "Dockerfile"):
  ```Dockerfile
  FROM alpine
  CMD ["sleep", "infinity"]
  ```
2. Create a bake file (named "docker-bake.hcl"):
  ```HCL
  target "default" {
    dockerfile = "Dockerfile"
    context = BAKE_CMD_CONTEXT
    tags = ["myimage:myversion"]
  }
  ```
3. Run `docker buildx bake`

**Expected outcome:**
The docker image specified should be built

**Actual outcome:**
```
ERROR: could not find cwd:: stat cwd:: no such file or directory
```

---

I looked into it a bit further, and it seems that when the aforementioned built-in variable was introduced, while the context [was arranged to be "cleaned"](https://github.com/docker/buildx/pull/671/files#diff-fbe2fa23203f2ff05f06b6c0731ea90529f90906807483db76a79f6018781465R581-R585) from the [cwd protocol](https://github.com/docker/buildx/pull/671/files#r668896194), the dockerfilePath is left with a cwd reference in it. Perhaps something as simple as adding a `!strings.HasPrefix(contextPath, "cwd://")` check [here](https://github.com/docker/buildx/pull/671/files#diff-fbe2fa23203f2ff05f06b6c0731ea90529f90906807483db76a79f6018781465R560) would be sufficient but take that with a pinch of salt as I'm not all that familiar with the codebase.

Also, if this variable was never meant to work in a local setting, please close this issue.

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #1627

Allow to use a local dockerfile with a remote bake definition like we do for context using `cwd://` protocol.

Can be tested with https://github.com/crazy-max/buildx-buildkit-tests/tree/main/buildx-1627:

```bash
$ cd /tmp
$ cat <<EOT >> Dockerfile.app
FROM scratch
COPY foo /foo
EOT
$ docker buildx bake https://github.com/crazy-max/buildx-buildkit-tests.git#:buildx-1627
```

### CODE REVIEW

File: bake/bake.go [hunk 1]
```diff
@@ -1048,6 +1050,17 @@ func toBuildOpt(t *Target, inp *Input) (*build.Options, error) {
 		bi.DockerfileInline = *t.DockerfileInline
 	}
 	updateContext(&bi, inp)
+	if strings.HasPrefix(bi.DockerfilePath, "cwd://") {
+		bi.DockerfilePath = path.Clean(strings.TrimPrefix(bi.DockerfilePath, "cwd://"))
+		if err := checkPath(bi.DockerfilePath); err != nil {
+			return nil, err
+		}
+		var err error
+		bi.DockerfilePath, err = filepath.Abs(bi.DockerfilePath)
```
Comment (crazy-max) [inline bake/bake.go:1059]: We need to return the absolute representation of the dockerfile path after checking its a valid one like we do for context so we can set the right dockerfile dir if context is a remote URL during build.

I was also thinking reading the file in `bi.DockerfileInline` and then set `bi.DockerfilePath = "-"` but that's hacky and would be confusing.

**Comment by jedevc** [comment]
Should we add a test to make sure that https://github.com/docker/buildx/pull/1880#issuecomment-1622000397 still applies? So in the test, if `Dockerfile.app` appears without the `cwd://` prefix, we should error. 

Either - that case should error like in v0.11 (which reverted #1880), or it should pull the docker file from the remote.

**Comment by crazy-max** [comment]
> Should we add a test to make sure that [#1880 (comment)](https://github.com/docker/buildx/pull/1880#issuecomment-1622000397) still applies? So in the test, if `Dockerfile.app` appears without the `cwd://` prefix, we should error.
> 
> Either - that case should error like in v0.11 (which reverted #1880), or it should pull the docker file from the remote.

Yes so for a remote bake definition like:

```hcl
target "default" {
  context = BAKE_CMD_CONTEXT
  dockerfile = "Dockerfile.app"
}
```

Invoked with:

```
docker buildx bake https://github.com/foo/bar.git
```

We should use local context but we don't support reading remote Dockerfile as expected:

```
#0 building with "default" instance using docker driver

#1 [internal] load git source https://github.com/foo/bar.git
#1 0.480 ref: refs/heads/main   HEAD
#1 0.480 dea0f6334d719a494a384a13812f604b6b79fed3       HEAD
#1 0.916 dea0f6334d719a494a384a13812f604b6b79fed3       refs/heads/main
#1 CACHED

#2 [internal] load .dockerignore
#2 transferring context:
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load build definition from Dockerfile.app
#3 transferring dockerfile: 2B done
#3 DONE 0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3004544897/Dockerfile.app: no such file or directory
```

File: bake/bake.go [hunk 2]
```diff
@@ -1048,6 +1050,21 @@ func toBuildOpt(t *Target, inp *Input) (*build.Options, error) {
...
+		if err != nil {
+			return nil, err
+		}
+	} else if !build.IsRemoteURL(bi.DockerfilePath) && strings.HasPrefix(bi.ContextPath, "cwd://") && (inp != nil && build.IsRemoteURL(inp.URL)) {
+		if _, err := os.Stat(filepath.Join(path.Clean(strings.TrimPrefix(bi.ContextPath, "cwd://")), bi.DockerfilePath)); err == nil {
+			return nil, errors.Errorf("reading a local dockerfile for a remote build invocation is not allowed when using a local context")
+		}
```
Comment (crazy-max) [inline bake/bake.go:1066]: Deny access to a local dockerfile for remote invocation with a local context. We need to check if a local Dockerfile exists early at the moment but in follow-up we should support reading a remote Dockerfile. Probably having a `DockerfileState` input like `ContextState` one.

File: tests/bake.go [hunk 3]
```diff
@@ -287,3 +290,101 @@ EOT
...
+	gitutil.GitCommit(git, t, "initial commit")
+	addr := gitutil.GitServeHTTP(git, t)
+
+	out, err := bakeCmd(
+		sb,
+		withDir(dirSrc),
+		withArgs(addr, "--set", "*.output=type=cacheonly"),
+	)
+	require.Error(t, err, out)
+	require.Contains(t, out, "reading a local dockerfile for a remote build invocation is not allowed when using a local context")
```
Comment (jedevc) [inline tests/bake.go:389]: I think this error message should probably be something like:

```suggestion
	require.Contains(t, out, "reading a dockerfile for a remote build invocation is not currently supported")
```

Since the plan is to have it default to reading it from the remote bake definition context right?

File: bake/bake.go (hunk 2 above)
Comment (jedevc) [reply bake/bake.go:1066]: Just want to check - isn't this independent of what the Context is set to? Isn't it instead dependent on whether the bake file is coming from a remote?

File: tests/bake.go (hunk 3 above)
Comment (crazy-max) [reply tests/bake.go:389]: Yes sounds good, will be more informative for the end user.

File: bake/bake.go (hunk 2 above)
Comment (crazy-max) [reply bake/bake.go]: It's dependent on remote bake but also if context is not local

**Comment by c-ameron** [comment]
Thanks so much for working on this! 😃

File: bake/bake.go [hunk 4]
```diff
@@ -1038,6 +1037,9 @@ func toBuildOpt(t *Target, inp *Input) (*build.Options, error) {
 	if t.Dockerfile != nil {
 		dockerfilePath = *t.Dockerfile
 	}
+	if !strings.HasPrefix(dockerfilePath, "cwd://") {
```
Comment (tonistiigi) [inline bake/bake.go:1040]: follow-up: this should work with remote URLs as well

File: bake/bake.go [hunk 5]
```diff
@@ -1048,6 +1050,21 @@ func toBuildOpt(t *Target, inp *Input) (*build.Options, error) {
...
+		bi.DockerfilePath = path.Clean(strings.TrimPrefix(bi.DockerfilePath, "cwd://"))
+		if err := checkPath(bi.DockerfilePath); err != nil {
+			return nil, err
+		}
+		var err error
+		bi.DockerfilePath, err = filepath.Abs(bi.DockerfilePath)
+		if err != nil {
+			return nil, err
+		}
+	} else if !build.IsRemoteURL(bi.DockerfilePath) && strings.HasPrefix(bi.ContextPath, "cwd://") && (inp != nil && build.IsRemoteURL(inp.URL)) {
```
Comment (tonistiigi) [inline bake/bake.go:1063]: I'm not sure I understand this condition:

> !build.IsRemoteURL(bi.DockerfilePath) && strings.HasPrefix(bi.ContextPath, "cwd://")

If Dockerfile is not remote and context is based on local dir then why would that be invalid config?

Maybe a comment would help.

File: bake/bake.go [hunk 6]
```diff
@@ -1048,6 +1050,21 @@ func toBuildOpt(t *Target, inp *Input) (*build.Options, error) {
...
+		if _, err := os.Stat(filepath.Join(path.Clean(strings.TrimPrefix(bi.ContextPath, "cwd://")), bi.DockerfilePath)); err == nil {
+			return nil, errors.Errorf("reading a dockerfile for a remote build invocation is currently not supported")
```
Comment (tonistiigi) [inline bake/bake.go:1065]: Is this for security?

Comment (crazy-max) [reply bake/bake.go:1065]: Yes, see https://github.com/docker/buildx/pull/2015#discussion_r1304145146

Comment (crazy-max) [reply bake/bake.go:1088]: Added a comment to better explain the issue.

**Review by tonistiigi — APPROVED** [review]
