### PR TITLE
bake: improve error message for empty definition

### LINKED ISSUE #2095: Bake should check for empty definition
Running bake without any definition in working dir:

```
$ docker buildx bake
ERROR: failed to find target default
```

```
$ docker buildx bake --set *.cache-from=type=gha
ERROR: could not find any target matching '*'
```

We should instead say that no definition has been provided/found.

### PR DESCRIPTION
**Pull request by dvdksn**
Closes #2095

Signed-off-by: David Karlsson <35727626+dvdksn@users.noreply.github.com>

### CODE REVIEW

File: commands/bake.go [hunk 1]
```diff
@@ -159,6 +159,10 @@ func runBake(dockerCli command.Cli, targets []string, in bakeOptions, cFlags com
 		return err
 	}
 
+	if len(files) < 1 {
```
Comment (crazy-max) [inline commands/bake.go:162]:
```suggestion
	if len(files) == 0 {
```

File: commands/bake.go [hunk 2]
```diff
@@ -159,6 +159,10 @@ func runBake(dockerCli command.Cli, targets []string, in bakeOptions, cFlags com
...
+		return errors.Errorf("couldn't find a bake definition")
```
Comment (crazy-max) [inline commands/bake.go:163]:
```suggestion
		return errors.New("couldn't find a bake definition")
```

File: tests/bake.go [hunk 3]
```diff
@@ -426,3 +427,9 @@ COPY foo /foo
 	require.Error(t, err, out)
 	require.Contains(t, out, "reading a dockerfile for a remote build invocation is currently not supported")
 }
+
+func testBakeEmpty(t *testing.T, sb integration.Sandbox) {
+	out, err := bakeCmd(sb)
+	require.Contains(t, out, "couldn't find a bake definition")
+	require.Error(t, err, out)
```
Comment (crazy-max) [inline tests/bake.go:434]: nit: I would swap these assertions

```suggestion
	require.Error(t, err, out)
	require.Contains(t, out, "couldn't find a bake definition")
```

**Review by crazy-max — APPROVED** [review]
