### PR TITLE
bake(compose): fix unskipped services without build context

### LINKED ISSUE #1276: Bake Error: "Failed to read Dockerfile" since 0.9.0 update
Hello!

First of all, thanks for all your hard work.

Since updating to v0.9.0 released yesterday, i get this error whenever I try to build with bake.

```
docker buildx bake -f docker-compose.yaml --load
[+] Building 0.0s (4/4) FINISHED                                                                                                                                                                         
 => [db internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 2B                                              0.0s
 => [db internal] load .dockerignore                                         0.0s
 => => transferring context: 2B                                                   0.0s
 => CANCELED [app internal] load .dockerignore                            0.0s
 => => transferring context: 2B                                                         0.0s
 => CANCELED [app internal] load build definition from Dockerfile                    0.0s
ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount1176813038/Dockerfile: no such file or directory
```

I can reproduce it both locally and in my CD/CI pipelines, and can confirm that the problem doesn't exist with version 0.8.2.

From comparing what is produced with the `--print` option from a simple Dockerfile with a custom app and a DB, it seems like buildx tries to build every single service, including ones that should not be built (i.e., in the docker-compose.yaml definitions, there is only an image specified for the service, and no "build" key). Then, when it can't find the Dockerfile for services that aren't meant to be built, it fails.

<details><summary>Output of `--print` on 0.8.2</summary>

```
docker buildx bake -f docker-compose.yaml --print
{
  "group": {
    "default": {
      "targets": [
        "app"
      ]
    }
  },
  "target": {
    "app: {
      "context": "app",
      "dockerfile": "Dockerfile",
      "tags": [
         "myapp"
      ]
    }
  }
}
```
</details>

<details><summary> Output of `--print` on 0.9.0</summary>

```
docker buildx bake -f docker-compose.yaml --print
{
  "group": {
    "default": {
      "targets": [
        "app",
        "db"
      ]
    }
  },
  "target": {
    "app: {
      "context": "app",
      "dockerfile": "Dockerfile",
      "tags": [
         "myapp"
      ]
    },
    "db": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "tags": [
        "postgres:14"
      ]
    }
  }
}
```

</details>

<details><summary>Files</summary>

docker-compose.yaml
```
version: "3.9"

services:
  app:
    image: myapp
    build:
      context: ./app

  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data

```

app/Dockerfile
```
FROM python:3.10-slim-bullseye-slim

RUN echo "Hello, World!"
```

</details>

<details><summary>My Docker Info</summary>

```
❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.0)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc sysbox-runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc version: v1.1.3-0-g6724737
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.18.0-4-amd64
 Operating System: Debian GNU/Linux bookworm/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.23GiB
 Name: [redacted]
 ID: [redacted]
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.25.0.0/16, Size: 24
```
</details>

Thank you for your help!

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #1276 

while fixing compose consistency check in https://github.com/docker/buildx/pull/1181 a regression was introduced where services without build context were taken into account.

it was not detected because our test `TestNoBuildOutOfTreeService` was not checking the targets length: https://github.com/docker/buildx/blob/611329fc7f1365556789bff4747f608d40cdc8a9/bake/compose_test.go#L71-L82

by fixing this issue we now remove the ability to merge compose files without a build context https://github.com/docker/buildx/issues/1172. To fix this we now parse compose files all together so the compose-go library can handle a proper sanity check on its side.

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

File: bake/hcl.go [hunk 1]
```diff
@@ -1,41 +1,11 @@
...
-		return f, true, err
-	}
-	if strings.HasSuffix(fn, ".hcl") {
-		f, diags := hclparse.NewParser().ParseHCL(dt, fn)
-		if diags.HasErrors() {
-			err = diags
-		}
-		return f, true, err
-	}
-	f, diags := hclparse.NewParser().ParseHCL(dt, fn+".hcl")
```
Comment (jedevc) [inline bake/hcl.go:28]: I think in the switch this logic gets dropped? I think we need to keep separate `case "hcl"` and `default` cases in the `switch filepath.Ext(strings.ToLower(f.Name)) {` above.

File: bake/bake.go [hunk 2]
```diff
@@ -200,52 +201,63 @@ func ParseFiles(files []File, defaults map[string]string) (_ *Config, err error)
...
 	return &c, nil
 }
 
 func dedupeConfig(c Config) Config {
 	c2 := c
+	c2.Groups = make([]*Group, 0, len(c2.Groups))
+	for _, g := range c.Groups {
+		g.Targets = dedupSlice(g.Targets)
+		c2.Groups = append(c2.Groups, g)
+	}
```
Comment (jedevc) [inline bake/bake.go:253]: As I read this, we need to make a non-destructive copy of `c`? If that's the case, we should deref and copy `g` before making changes to `g.Targets`.

File: bake/hcl.go (hunk 1 above)
Comment (crazy-max) [reply bake/hcl.go:28]: I was wondering why we have this fallback to json if hcl parsing fails. Looks like a best effort if user don't use a known extension. I'll bring it back.

File: bake/bake.go [hunk 3]
```diff
@@ -256,24 +272,23 @@ func ParseFile(dt []byte, fn string) (*Config, error) {
 	return ParseFiles([]File{{Data: dt, Name: fn}}, nil)
 }
 
-func ParseComposeFile(dt []byte, fn string) (*Config, bool, error) {
+func ParseComposeFile(dt []byte, fn string) (bool, error) {
```
Comment (jedevc) [inline bake/bake.go:275]: I like the idea of keeping a smaller footprint for this patch, but as this doesn't return a `Config` struct anymore, I think this might make more sense as `Validate`/etc instead of `Parse`?

May also be worth keeping as a private function IMO.

**Review by jedevc — APPROVED** [review]

**Review by tonistiigi — APPROVED** [review]
