### PR TITLE
Fix k8s driver with certs cannot boot

### LINKED ISSUE #1800: Kubernetes self-signed certificate not copied to container
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When creating a buildx kubernetes builder with a config file for private docker registry, the custom config is mounted to the build pod however certificates are not available. Looking at the deployment 2x configmaps are created, but only 1x is mounted.

Example buildx command:

```sh
docker buildx create \
  --bootstrap \
  --use \
  --name kube \
  --driver kubernetes \
  --config /etc/buildkit/buildkitd.toml \
  '--driver-opt="nodeselector=docker/buildkit=","namespace=buildkit"'
```

### Expected behaviour

Custom certificates should be mounted at `/etc/buildkit/certs/<registry>/`

### Actual behaviour

There are no certificates mounted in the pod.

### Buildx version

github.com/docker/buildx v0.10.4 c513d34

### Docker info

```text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 233
  Running: 166
  Paused: 0
  Stopped: 67
 Images: 780
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-73-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 125.7GiB
 Name: server-01
 ID: 6HQ7:ELB5:WJFJ:2CIK:SCF6:STIS:G57Q:3UNX:AJXY:4BYQ:6JCJ:YR3U
 Docker Root Dir: /srv/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  dockerregistry-01:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
NAME/NODE   DRIVER/ENDPOINT                            STATUS  BUILDKIT PLATFORMS
kube *      kubernetes                                                  
  kube0     kubernetes:///kube?deployment=&kubeconfig= running v0.11.6  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
default     docker                                                      
  default   default                                    running 23.0.6   linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

### Configuration

Config `/etc/buildkit/buildkitd.toml`:

```toml
debug = true
[registry."dockerregistry-01"]
  ca=["/etc/certs/cluster-signer.crt"]
  [[registry."dockerregistry-01".keypair]]
    key="/etc/certs/dockerregistry-01.key"
    cert="/etc/certs/dockerregistry-01.crt"
```

### Build logs

_No response_

### Additional info

Lines missing in deployment:

```yaml
spec:
  template:
    spec:
      volumes:
      - name: config-1
          configMap:
            name: kube0-config-1
      containers:
      - name: buildkitd
        volumeMounts:
        - name: config-1
          mountPath: /etc/buildkit/certs/dockerregistry-01
```

### PR DESCRIPTION
**Pull request by kariya-mitsuru**
When a self-signed certificate is specified in `buildkitd.toml`, the current implementation registers the certificate as a `ConfigMap`, but the `volumes` and `volumeMounts` in `Deployment` are incorrect, so the `Deploymetnt` cannot start.

This fixes #1800.

### CODE REVIEW

File: driver/kubernetes/manifest/manifest.go [hunk 1]
```diff
@@ -148,21 +148,21 @@ func NewDeployment(opt *DeploymentOpt) (d *appsv1.Deployment, c []*corev1.Config
...
+		d.Spec.Template.Spec.Containers[0].VolumeMounts = append(d.Spec.Template.Spec.Containers[0].VolumeMounts, corev1.VolumeMount{
 			Name:      cfg.name,
 			MountPath: path.Join("/etc/buildkit", cfg.path),
-		}}
+		})
 
-		d.Spec.Template.Spec.Volumes = []corev1.Volume{{
-			Name: "config",
+		d.Spec.Template.Spec.Volumes = append(d.Spec.Template.Spec.Volumes, corev1.Volume{
+			Name: cfg.name,
```
Comment (crazy-max) [inline driver/kubernetes/manifest/manifest.go:157]: Seems fine to use `cfg.name` here. Might have been an oversight in https://github.com/docker/buildx/pull/824 (cc @tonistiigi @morlay)

**Review by crazy-max — COMMENTED** [review]
Not really familiar with k8s deployments but looking at changes in https://github.com/docker/buildx/pull/787 and follow-up for k8s driver in https://github.com/docker/buildx/pull/824, it looks good.

PTAL @tonistiigi @morlay

**Review by crazy-max — APPROVED** [review]
