### PR TITLE
policy: mark policy progress vertex on DENY build failures

### LINKED ISSUE #3644: Policy: associate policy error with the build step progress item
Currently, the policy error just shows up at the end of the build, and none of the build steps are marked as failing. This can be confusing and also hides the last logs for policy evaluation (or makes them appear in the middle of plain progress).

Not really how to implement this yet, as policy evaluation failing doesn't necessarily mean build will fail as well, and build error itself comes from a different codepath than the policy evaluation.

### PR DESCRIPTION
**Pull request by tonistiigi**
fix #3644

Track denied source identifiers during policy evaluation and flag the policy progress vertex as failed when BuildKit returns a matching DENY error pattern.

This improves the progress output of policy error and shows last policy logs with the build error.

### CODE REVIEW

File: policy/policy_error_test.go [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+			Source: &solverpb.SourceOp{
+				Identifier: "docker-image://busybox:latest",
+			},
+		},
+	}
+	p.recordDenyIdentifier(req)
+
+	err := errors.New("failed to solve: error evaluating the source policy: source \"docker-image://alpine:latest\" not allowed by policy: action DENY")
+	require.False(t, p.IsPolicyError(err))
+}
```
Comment (crazy-max) [inline policy/policy_error_test.go]: nit: these tests look like a good fit for a single table-driven test (`[]struct{name, err, want}`) since setup is identical across cases. And could maybe also moved to `validate_test.go` and named `func TestPolicyIsPolicyError`?

**Comment by crazy-max** [comment]
Could we have an integration test around the `release(err)/policyLogger.Close(inErr)` flow? Similar to https://github.com/docker/buildx/blob/a0103f4278354ae00a2325e26e07f87b1674d1a2/tests/build.go#L645 just to test progress.

**Comment by tonistiigi** [comment]
Added progress integration test and refactored unit test.

**Comment by crazy-max** [comment]
Seems there is a deadlock in sourcemeta resolver, opened #3659

**Comment by tonistiigi** [comment]
Fix for that deadlock is in #3657. If you want, I can pull it out, but #3657 has some other changes to `sourcemeta` as well that would cause rebase conflicts.

**Review by crazy-max — APPROVED** [review]
