### PR TITLE
Updates and fixes to policy support

### LINKED ISSUE #3567: Rego source policy additional UX
This issue is to discuss UX changes for #3539 for additional control and helpers.

## Build

`build` and `bake` automatically load a default policy file based on the Dockerfile path(if one exists):

    Dockerfile        → Dockerfile.rego
    foo.Dockerfile    → foo.Dockerfile.rego

When building from a remote context, these files are also loaded from a remote context, like the Dockerfile.

Users may override or extend this behavior using:

    --policy [csv] [--policy [csv]]...

#### `filename=<path>`
Add a policy file.  Can be combined with `reset`.

#### `reset=<bool>`
If set, the currently loaded policy (eg. the default based on Dockerfile) is ignored and the policy set is replaced.  
After `reset=true`, only explicitly provided `filename=` entries are used.

#### `disabled=<bool>`
Disable policy evaluation entirely.  Using this together with other policy flags is an error.

#### `strict=<bool>`
Require policy enforcement.  
If `true`, builds fail when running against a BuildKit that does not support policies.  
Policy file load or compile errors always fail regardless of this setting.
Initially, this will default to `false` but may change somewhere in the future where BuildKit instances without policy support become a rarity.

#### `log-level=<level>`
Set policy logging verbosity (e.g., `debug`).

---

#### `ignore=<expr>`
Example:

    --policy ignore=image.repo=alpine

Potential mechanism for skipping specific sources when generating the policy input.  
Not sure if we need smth. like this.

---

## Policy Subcommand

These commands help writing policies and ensuring that they continue to work correctly after code changes.

### `buildx policy print-schema`
Print the JSON schema describing the policy input object.

### `buildx policy test <path>`
Execute a `_test.rego` file with fixed inputs, similar to `opa test`.  
Inputs are not fetched via BuildKit, but part of the test already.

### `buildx policy eval --filename=<name> [--print] [source]`
Evaluate the specified policy against the input for `source`.

- These are the same source values as can be specified in `--build-context`.  
  The source is resolved in BuildKit and then checked against the policy definition.

- If `--print` is set, the policy isn’t evaluated; the input object is printed instead.  
  Useful for exploring and validating values that policies are written against or for capturing input definitions for tests.

- If `source` is not specified, the command expects an input object JSON on stdin.

@crazy-max @dvdksn @AkihiroSuda @colinhemmings

### LINKED ISSUE #3613: policy eval fails with "object required" when checking attestation fields on v2 manifest images
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

- related to moby/buildkit#6472

`docker buildx policy eval` with a policy that checks attestation fields (hasProvenance, signatures) on images using v2 manifest format fails. These fields should be unavailable/unresolved for v2 manifest images. Accessing them causes an error.

### Expected behaviour

I guess there's two issues here.

- It probably shouldn't error because of the image format.
- Afaict `eval` doesn't actually resolve `hasProvenance` so it should probably print an info/warn? eg:

```
WARNING: Policy evaluation incomplete - unresolved fields: image.hasProvenance
```

### Actual behaviour

```bash
# images with oci indexes silently exit:
docker buildx policy eval docker-image://alpine:3.19
# images with manifest lists cause an error
docker buildx policy eval docker-image://davidkarlsson416/image-no-provenance
ERROR: object required
```

### Buildx version

github.com/docker/buildx v0.31.0-rc1 b9b24359ba6441ef97086ee50db216c026ca388d

### Docker info

```text

```

### Builders list

```text
NAME/NODE           DRIVER/ENDPOINT     STATUS    BUILDKIT      PLATFORMS
v0.27.0-rc1*        docker-container                            
 \_ v0.27.0-rc1      \_ desktop-linux   running   v0.27.0-rc1   linux/amd64 (+2), linux/arm64, linux/arm (+2), linux/ppc64le, (3 more)
default             docker                                      
 \_ default          \_ default         running   v0.26.2       linux/amd64 (+2), linux/arm64, linux/ppc64le, linux/s390x, (2 more)
desktop-linux       docker                                      
 \_ desktop-linux    \_ desktop-linux   running   v0.26.2       linux/amd64 (+2), linux/arm64, linux/ppc64le, linux/s390x, (2 more)
```

### Configuration

```
$ cat > Dockerfile.rego << 'EOF'
package docker
default allow := false
allow if input.local
allow if input.image.hasProvenance
decision := {"allow": allow}
EOF
$ docker buildx policy eval docker-image://alpine:3.19
$ docker buildx policy eval docker-image://davidkarlsson416/image-no-provenance
ERROR: object required

### Build logs

```text

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by tonistiigi**
@crazy-max @dvdksn 

Review per commit.

fixes #3613
fixes https://github.com/docker/buildx/issues/3567#issuecomment-3754226824

### CODE REVIEW

File: policy/builtin_module.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
+package policy
+
+import "github.com/open-policy-agent/opa/v1/ast"
+
+const builtinPolicyModuleFilename = "builtin/buildx_defaults.rego"
+
+const builtinPolicyModule = `package docker
```
Comment (crazy-max) [inline policy/builtin_module.go]: Maybe use [embed](https://pkg.go.dev/embed) for this?

File: policy/validate.go [hunk 2]
```diff
@@ -308,11 +303,38 @@ func (p *Policy) CheckPolicy(ctx context.Context, req *policysession.CheckPolicy
...
+		pl = platforms.Normalize(pl)
+		return &pl, nil
+	}
+	return nil, nil
+}
+
+func sourceName(req *policysession.CheckPolicyRequest) string {
+	name := req.Source.Source.Identifier
+	if p, _ := platformFromReq(req); p != nil {
+		name += " (" + platforms.Format(*p) + ")"
```
Comment (crazy-max) [inline policy/validate.go:335]:
```
#11 [linux/arm64 stage-1 1/3] FROM docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
#11 resolve docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 0.1s done
#11 DONE 0.1s

#12 [linux/arm64 stage-1 2/3] COPY --from=xx / /
#12 CACHED

#13 [linux/arm64 stage-1 3/3] RUN touch foo
#13 CACHED

#1 loading policies 10-xx-external.Dockerfile.rego
#1 0.626 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.627 10-xx-external.Dockerfile.rego:12: alpine false
#1 0.627 policy decision for source docker-image://docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 (linux/amd64): ALLOW
#1 0.627 10-xx-external.Dockerfile.rego:12: tonistiigi/xx true
#1 0.627 10-xx-external.Dockerfile.rego:12: alpine false
#1 0.627 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.627 policy decision for source docker-image://docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 (linux/amd64): ALLOW
#1 0.627 policy decision for source docker-image://docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 (linux/arm64): ALLOW
#1 0.628 10-xx-external.Dockerfile.rego:12: tonistiigi/xx true
#1 0.628 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.628 policy decision for source docker-image://docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 (linux/amd64): ALLOW
```

It would be better as prefix imo to be consistent with build stages, WDYT?

```
#11 [linux/arm64 stage-1 1/3] FROM docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
#11 resolve docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 0.1s done
#11 DONE 0.1s

#12 [linux/arm64 stage-1 2/3] COPY --from=xx / /
#12 CACHED

#13 [linux/arm64 stage-1 3/3] RUN touch foo
#13 CACHED

#1 loading policies 10-xx-external.Dockerfile.rego
#1 0.626 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.627 10-xx-external.Dockerfile.rego:12: alpine false
#1 0.627 [linux/amd64] policy decision for source docker-image://docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62: ALLOW
#1 0.627 10-xx-external.Dockerfile.rego:12: tonistiigi/xx true
#1 0.627 10-xx-external.Dockerfile.rego:12: alpine false
#1 0.627 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.627 [linux/amd64] policy decision for source docker-image://docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6: ALLOW
#1 0.627 [linux/arm64] policy decision for source docker-image://docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62: ALLOW
#1 0.628 10-xx-external.Dockerfile.rego:12: tonistiigi/xx true
#1 0.628 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.628 [linux/amd64] policy decision for source docker-image://docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6: ALLOW
```

File: policy/validate.go [hunk 3]
```diff
@@ -91,16 +91,11 @@ func (p *Policy) CheckPolicy(ctx context.Context, req *policysession.CheckPolicy
...
+		pl, err := platformFromReq(req)
 		if err != nil {
-			return nil, nil, errors.Wrapf(err, "failed to parse platform")
+			return nil, nil, err
 		}
-		pl = platforms.Normalize(pl)
-		platform = &pl
+		platform = pl
 	} else {
 		platform = p.opt.DefaultPlatform
```
Comment (crazy-max) [inline policy/validate.go:100]:
```
#7 [xx 1/1] FROM docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#7 resolve docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 0.0s done
#7 DONE 0.0s

#8 [stage-1 2/3] COPY --from=xx / /
#8 CACHED

#9 [stage-1 3/3] RUN touch foo
#9 CACHED

#1 loading policies 10-xx-external.Dockerfile.rego
#1 0.813 10-xx-external.Dockerfile.rego:12: tonistiigi/xx true
#1 0.813 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.813 policy decision for source docker-image://docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 (linux/amd64): ALLOW
#1 0.813 10-xx-external.Dockerfile.rego:12: alpine false
#1 0.813 policy decision for source docker-image://docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 (linux/amd64): ALLOW
#1 DONE 1.1s
```

If no platform set I guess we should not display the default platform in progress output to be consistent with build stages:

```
#7 [xx 1/1] FROM docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#7 resolve docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 0.0s done
#7 DONE 0.0s

#8 [stage-1 2/3] COPY --from=xx / /
#8 CACHED

#9 [stage-1 3/3] RUN touch foo
#9 CACHED

#1 loading policies 10-xx-external.Dockerfile.rego
#1 0.813 10-xx-external.Dockerfile.rego:12: tonistiigi/xx true
#1 0.813 hack/utils.rego:4: compare sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6 add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6
#1 0.813 policy decision for source docker-image://docker.io/tonistiigi/xx:1.8.0@sha256:add602d55daca18914838a78221f6bbe4284114b452c86a48f96d59aeb00f5c6: ALLOW
#1 0.813 10-xx-external.Dockerfile.rego:12: alpine false
#1 0.813 policy decision for source docker-image://docker.io/library/alpine:latest@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62: ALLOW
#1 DONE 1.1s
```

File: policy/builtin_module.go (hunk 1 above)
Comment (tonistiigi) [reply policy/builtin_module.go]: updated

File: policy/validate.go (hunk 2 above)
Comment (tonistiigi) [reply policy/validate.go:335]: I guess we can improve this further in other follow-ups. The platform is specific to the image source, not like the build output where the step is part of a build request to a specific platform. Maybe putting the source name at the beginning of the text would improve.

**Review by jsternberg — APPROVED** [review]
Approving since this has already been reviewed by @crazy-max and he's out for the week. It LGTM but I don't have the most detailed understanding of this domain.
